import { arcanaLabel } from "@/lib/arcana";

/** Развёрнутое описание аркана в 12 сферах жизни */
export interface ArcanaDepth {
  personality: string;
  character: string;
  health: string;
  love: string;
  money: string;
  purpose: string;
  talents: string;
  family: string;
  children: string;
  career: string;
  karma: string;
  spirit: string;
  practice: string;
}

export const ARCANA_DEPTH: Record<number, ArcanaDepth> = {
  1: {
    personality: "Лидерская аура, уверенный взгляд. Люди видят в тебе инициатора и человека действия.",
    character: "Внутри — воля и потребность создавать. Раздражает пассивность и нерешительность других.",
    health: "Энергия в голове и руках. Риск — перегруз нервной системы от постоянного «надо успеть».",
    love: "Притягиваешь партнёров, которым нужен сильный рядом. Важно не подавлять, а вдохновлять.",
    money: "Деньги приходят через личную инициативу, проекты, лидерство. Пассивный доход требует делегирования.",
    purpose: "Миссия — начинать, вести, показывать пример. Ты здесь, чтобы материализовать идеи.",
    talents: "Организация, старт проектов, публичные выступления, продажи, управление.",
    family: "В роду — тема власти и ответственности. Ты можешь стать «опорой» или разорвать сценарий контроля.",
    children: "К детям — высокие ожидания. Учись принимать их путь, а не свой сценарий успеха.",
    career: "Предпринимательство, руководство, любая роль «первого». Не терпишь подчинённого без смысла.",
    karma: "Урок — сила без эгоизма. Прошлые паттерны контроля и манипуляции прорабатываются через служение.",
    spirit: "Комфорт — в действии и осознанной воле. Медитация «я выбираю» заземляет.",
    practice: "Ежедневно одно маленькое «начало» без давления на результат.",
  },
  2: {
    personality: "Тихая загадочность, глубокий взгляд. Окружающие чувствуют интуицию, даже если ты молчишь.",
    character: "Богатый внутренний мир, потребность в уединении. Эмоции часто скрыты за спокойствием.",
    health: "Чувствительная нервная система, гормональный фон реагирует на стресс. Важен сон и тишина.",
    love: "Нужна эмоциональная безопасность. Любовь через тонкую связь, а не громкие жесты.",
    money: "Доход через интуицию, консультирование, психологию, творчество, работу с информацией.",
    purpose: "Раскрывать тайное, быть проводником знаний и глубины.",
    talents: "Интуиция, письмо, исследование, психология, эзотерика, дизайн.",
    family: "Родовая тема — невысказанные секреты, женская линия, молчание.",
    children: "Глубокая эмпатия к детям. Риск — проецировать свои страхи.",
    career: "Аналитика, творчество, наука, терапия. Нужна автономия и тишина.",
    karma: "Урок — говорить правду мягко, не прятаться в тени.",
    spirit: "Комфорт — в тишине, у воды, в дневнике.",
    practice: "Записывай сны и инсайты — они твой навигатор.",
  },
  3: {
    personality: "Мягкость, эстетика, тепло. Создаёшь вокруг себя атмосферу уюта и принятия.",
    character: "Забота, чувственность, потребность в красоте. Можешь растворяться в других.",
    health: "Женская энергия, репродуктивная система, горло. Важны питание и удовольствие без вины.",
    love: "Любишь щедро и глубоко. Нужен партнёр, который ценит заботу, а не пользуется ею.",
    money: "Изобилие через творчество, красоту, сферу услуг, работу с телом и домом.",
    purpose: "Создавать и плодить — проекты, детей, идеи, пространства.",
    talents: "Искусство, кулинария, дизайн, воспитание, event, floristics.",
    family: "Сильная связь с материнской линией. Тема — забота vs созависимость.",
    children: "Природный дар родительства. Учись границам «я / ребёнок».",
    career: "Творческие и helping-профессии. Деньги растут с самоценностью.",
    karma: "Урок — любить себя наравне с другими.",
    spirit: "Комфорт — в природе, творчестве, объятиях.",
    practice: "Один act of self-care в день без оправданий.",
  },
  4: {
    personality: "Надёжность, собранность, авторитет. На тебя можно положиться.",
    character: "Потребность в порядке и правилах. Страх хаоса может делать жёстким.",
    health: "Кости, суставы, спина. Тело просит режим и движение.",
    love: "Любовь через стабильность и верность. Сложно с непредсказуемыми партнёрами.",
    money: "Деньги через систему, недвижимость, госслужбу, строительство, финансы.",
    purpose: "Строить структуры, которые переживут тебя.",
    talents: "Менеджмент, право, инженерия, администрирование.",
    family: "Родовой паттерн — «должен», дисциплина, строгость.",
    children: "Даёшь опору, но важно не подавлять спонтанность.",
    career: "Карьера через иерархию и экспертизу. Лучше — свой «имперium».",
    karma: "Урок — гибкость и тепло внутри структуры.",
    spirit: "Комфорт — в порядке дома и ясных правилах.",
    practice: "Раз в неделю — день без жёсткого плана.",
  },
  5: {
    personality: "Мудрый наставник, спокойный собеседник. Излучаешь авторитет знаний.",
    character: "Ценности и традиции важны. Внутренний критик силён, если идёшь «не туда».",
    health: "Горло, щитовидка, осанка. Голос должен звучать — пой, говори.",
    love: "Нужен партнёр с общими ценностями. Романтика через уважение и обучение друг друга.",
    money: "Доход через обучение, консалтинг, духовные практики, юриспруденцию.",
    purpose: "Быть мостом между знанием и людьми.",
    talents: "Педагогика, коучинг, религия, философия, writing.",
    family: "Род — хранители традиций. Ты выбираешь: повторить или обновить.",
    children: "Естественный учитель для детей. Не навязывай dogma.",
    career: "Эксперт, наставник, методист. Репутация — главный капитал.",
    karma: "Урок — жить своими ценностями, а не чужими.",
    spirit: "Комфорт — в храме, библиотеке, кругу единомышленников.",
    practice: "Учи только то, что прожил сам.",
  },
  6: {
    personality: "Обаяние, дипломатичность, эстетика отношений. Люди тянутся за гармонией.",
    character: "Внутренний выбор — постоянная тема. Страх ошибиться в любви.",
    health: "Сердце, кожа, почки. Эмоции напрямую бьют по телу.",
    love: "Центральная тема жизни. Партнёрство — зеркало и урок.",
    money: "Деньги через партнёрства, beauty, event, посредничество.",
    purpose: "Создавать гармонию и помогать другим выбирать сердцем.",
    talents: "Дипломатия, дизайн, психология отношений, стилистика.",
    family: "Родовые сценарии «идеальной семьи» vs реальность.",
    children: "Любовь к детям сильна. Учись не idealize.",
    career: "HR, медиация, индустрия красоты, парный бизнес.",
    karma: "Урок — честный выбор, а не угождение.",
    spirit: "Комфорт — в паре или в красоте пространства.",
    practice: "Перед решением — «что хочу я, не другие?»",
  },
  7: {
    personality: "Динамика, напор, целеустремлённость. Заряжаешь пространство движением.",
    character: "Внутренний двигатель не останавливается. Сложно сидеть на месте.",
    health: "Ноги, сердце, adrenals. Риск выгорания и травм от спешки.",
    love: "Страсть и drive. Нужен партнёр, который не тормозит, но заземляет.",
    money: "Деньги через активность, спорт, логистику, продажи, travel.",
    purpose: "Побеждать inertia — свою и мира.",
    talents: "Спорт, бизнес, маркeting, военное дело, transport.",
    family: "Род — гонка, достижения, «будь лучшим».",
    children: "Мотивируешь детей, но не перегрей с давлением.",
    career: "Карьера- марафон с рывками. Нужны цели и отдых.",
    karma: "Урок — победа над собой, не над другими.",
    spirit: "Комфорт — в движении: бег, дорога, цель.",
    practice: "Один день в неделю — без задач и KPI.",
  },
  8: {
    personality: "Серьёзность, честность, внутренний стержень. Считывается кармическая глубина.",
    character: "Сильное чувство справедливости. Обиды запоминаются надолго.",
    health: "Почки, поясница, кожа. Тело хранит нерешённые конфликты.",
    love: "Нужна честность и равенство. Предательство переживается тяжело.",
    money: "Деньги через право, audit, страхование, работу с долгами.",
    purpose: "Восстанавливать баланс — в себе и в мире.",
    talents: "Юриспруденция, бухгалтерия, investigative, HR-compliance.",
    family: "Родовые обиды и «непрощённые» истории.",
    children: "Учишь fairness. Покажи прощение на примере.",
    career: "Системы контроля, финансы, судебная сфера.",
    karma: "Урок — отпустить осуждение.",
    spirit: "Комфорт — в ясности и честном разговоре.",
    practice: "Письмо прощения (можно не отправлять).",
  },
  9: {
    personality: "Мудрость, отстранённость, глубина. Ощущение «старой души».",
    character: "Потребность в solitude. Не всегда понятен окружающим.",
    health: "Иммунитет, суставы. Устаёшь от шума и суеты.",
    love: "Нужен партнёр, уважающий пространство. Близость — медленно и глубоко.",
    money: "Деньги через экспертность, research, наставничество, IT.",
    purpose: "Нести свет знания, не теряя себя.",
    talents: "Наука, философия, программирование, аналитика.",
    family: "Род — одиночество, отшельники, учёные.",
    children: "Можешь поздно или осознанно. Дети учат открываться.",
    career: "Эксперт, исследователь, writer. Удалёнка — идеал.",
    karma: "Урок — выходить к людям, не теряя глубины.",
    spirit: "Комfort — в горах, книгах, тишине.",
    practice: "Один социальный контакт в неделю «из сердца».",
  },
  10: {
    personality: "Лёгкость, адаптивность, ощущение «везунчика» или «качелей».",
    character: "Emotional swings. Жизнь — циклы подъёмов и спадов.",
    health: "Нервная система, аллергии. Режим стабилизирует.",
    love: "Судьбоносные встречи. Отношения меняются с циклами.",
    money: "Нестабильный поток без системы. Удача + риск.",
    purpose: "Учиться танцевать с переменами.",
    talents: "Event, trading, travel, entertainment, crisis-management.",
    family: "Род — резкие повороты судьбы, эмиграции.",
    children: "Гибкость с детьми. Стабильный ритual дома важен.",
    career: "Профессии с циклами. Несколько источников дохода.",
    karma: "Урок — ответственность в момент подъёма.",
    spirit: "Комфорт — принимать flow жизни.",
    practice: "Финансовая подушка на «зиму цикла».",
  },
  11: {
    personality: "Магнетизм, внутренняя сила, спокойная уверенность.",
    character: "Эмоции мощные, но скрытые. Взрыв после долгого терпения.",
    health: "Сердце, давление, зубы. Нужен выход эмоциям.",
    love: "Страсть и loyalty. Ревность — тень.",
    money: "Деньги через личный бренд, управление, work с массами.",
    purpose: "Управлять энергией — своей и коллективной.",
    talents: "Лидерство, politics, stage, coaching, veterinary.",
    family: "Род — подавленный гнев или сила без слов.",
    children: "Сильная связь. Учи здоровой агрессии.",
    career: "Власть, influence, public role.",
    karma: "Урок — мягкая сила вместо подавления.",
    spirit: "Комфорт — работа с телом и дыханием.",
    practice: "Спорт или martial arts для сливa tension.",
  },
  12: {
    personality: "Нестандартность, creativный взгляд. Можешь казаться «не отсюда».",
    character: "Периоды пауз и insight. Жертвенность — тень.",
    health: "Лимфа, feet, insomnia. Тело просит смены perspective.",
    love: "Кarmические связи, уроки через паузы.",
    money: "Деньги приходят после pivot. Не линейный путь.",
    purpose: "Видеть иначе и показывать новый угол.",
    talents: "Art, cinema, therapy, volunteer, astrology.",
    family: "Род — «застряли», жертвы, нестандартные судьбы.",
    children: "Особые дети или нестандартный путь к родительству.",
    career: "Творчество, помогающие профессии, sabbatical нормален.",
    karma: "Урок — действие после insight.",
    spirit: "Комфорт — в подвешенном состоянии творчества.",
    practice: "Раз в месяц — день «ничего не делать» осознанно.",
  },
  13: {
    personality: "Трансформатор, magnet for change. Рядом — всё меняется.",
    character: "Страх и тяга к переменам одновременно.",
    health: "Detox organs, spine. Тело требует чисток и обновлений.",
    love: "Отношения через кризисы к renewal.",
    money: "Резкие финансовые трансформации. Не держись за старое.",
    purpose: "Завершать циклы и освобождать место новому.",
    talents: "Medicine, surgery, crisis-coach, recycling, renovation.",
    family: "Род — потери, разрывы, transgenerational trauma.",
    children: "Тема трансформации через детей или их отсутствие.",
    career: "Профессии «до/после». Частые pivots.",
    karma: "Урок — добровольное отпускание.",
    spirit: "Комфорт — в ритualax завершения.",
    practice: "Раз в сезон — расхламление и символическое «сжигание» старого.",
  },
  14: {
    personality: "Спокойствие, дипломат, исцеляющее присутствие.",
    character: "Стремление к balance. Прокрастинация — тень.",
    health: "Печень, metabolism. Умеренность во всём — ключ.",
    love: "Гармоничные отношения возможны при терпении.",
    money: "Стабильный рост без резких скачков. Alchemy финансов.",
    purpose: "Соединять противоположности.",
    talents: "Medicine, chemistry, cooking, mediation, design.",
    family: "Род — качели, алкоголь/зависимости или healers.",
    children: "Баланс strictness и freedom.",
    career: "Долгая дистанция. Не спеши — результат устойчив.",
    karma: "Урок — решительность в меру.",
    spirit: "Комфорт — в water, art, moderate life.",
    practice: "Правило «достаточно хорошо» вместо perfect.",
  },
  15: {
    personality: "Магнетизм, sensuality, charisma. Внимание притягивается легко.",
    character: "Сильные желания и тени. Зависимости — зона риска.",
    health: "Reproductive, hormones, skin. Тело и pleasure связаны.",
    love: "Страсть, jealousy, deep bonding. Тень — manipulation.",
    money: "Большие деньги и большие риски. Не играй all-in.",
    purpose: "Интегрировать тень и научиться свободе без цепей.",
    talents: "Show-biz, finance, psychology, luxury, tantra.",
    family: "Род — секреты, зависимости, taboo.",
    children: "Strong karmic theme. Honesty breaks cycles.",
    career: "High stakes industries. Ethics — foundation.",
    karma: "Урок — осознанность желаний.",
    spirit: "Комфорт — в honest shadow work.",
    practice: "Список «что контролирует меня» — раз в месяц.",
  },
  16: {
    personality: "Intensity, breakthrough energy. «Гром среди ясного неба».",
    character: "Кrizis as teacher. Сопротивление change больно.",
    health: "Head, spine, pressure. Acute episodes после stress.",
    love: "Stormy passion или резкие разрывы. Truth above all.",
    money: "Потери и rebuild. Не строй на sand.",
    purpose: "Разрушать false и строить на truth.",
    talents: "Emergency, construction, activism, radical change.",
    family: "Род — катастрофы, резкие повороты, heroes.",
    children: "Protect детей от family drama.",
    career: "Кrizis-manager. После breakdown — breakthrough.",
    karma: "Урок — принимать truth раньше, чем башня упадёт.",
    spirit: "Комфорт — в honesty и minimalism.",
    practice: "Еженедельный audit «на чём стою — правда или illusion?»",
  },
  17: {
    personality: "Hope, inspiration, «light in eyes». People trust your vision.",
    character: "Dreamer with need for grounding.",
    health: "Vision, sleep, legs. Rest restores faith.",
    love: "Romantic idealism. Partner as muse.",
    money: "Деньги следуют за inspiration. Don't wait passively.",
    purpose: "Нести hope и показывать путь к мечте.",
    talents: "Art, music, astrology, coaching, invention.",
    family: "Род — dreamers или broken dreams.",
    children: "Inspire детей верить в себя.",
    career: "Creative + public. Visibility helps income.",
    karma: "Урок — мечта + action.",
    spirit: "Комфорт — под stars, у water.",
    practice: "Один шаг к мечте каждую неделю.",
  },
  18: {
    personality: "Mystery, emotionality, artistic aura.",
    character: "Rich subconscious. Fears need light.",
    health: "Psyche, sleep, water balance. Psychosomatics.",
    love: "Deep emotional waves. Need safe partner.",
    money: "Irregular flow. Intuition in investments.",
    purpose: "Work with subconscious and heal fears.",
    talents: "Psychology, art, film, poetry, healing.",
    family: "Род — fears, illusions, mystics.",
    children: "Sensitive children need calm environment.",
    career: "Night shifts ok. Creative cycles.",
    karma: "Урок — distinguish intuition from anxiety.",
    spirit: "Комфорт — moon, water, journal.",
    practice: "Grounding: feet on floor, 5-4-3-2-1 senses.",
  },
  19: {
    personality: "Radiance, joy, charisma. Center of attention naturally.",
    character: "Need for recognition. Burnout if always «on».",
    health: "Heart, eyes, back. Sun and rest vital.",
    love: "Warm generous love. Partner must celebrate you.",
    money: "Success brings money. Don't attach worth to applause.",
    purpose: "Shine and give warmth without ego.",
    talents: "Stage, kids, politics, solar businesses, sport.",
    family: "Род — pride or hidden shame.",
    children: "Natural with children. Play restores soul.",
    career: "Public roles. Vacation mandatory.",
    karma: "Урок — inner sun без external validation.",
    spirit: "Комfort — sun, laughter, creativity.",
    practice: "Daily «what made me happy for myself».",
  },
  20: {
    personality: "Awakening energy, sense of calling.",
    character: "Self-judgment heavy. Second chances theme.",
    health: "Hearing, throat, immunity. Voice must sound.",
    love: "Karmic meetings. Forgiveness in pairs.",
    money: "Income after calling found. Before — confusion.",
    purpose: "Answer the call — career of soul.",
    talents: "Music, law, medicine, spiritual work.",
    family: "Род — unredeemed guilt, second chances.",
    children: "Children as teachers of forgiveness.",
    career: "Pivot to meaning. Late bloom ok.",
    karma: "Урок — forgive self and act now.",
    spirit: "Комfort — bells, meditation, nature.",
    practice: "Morning question: «what calls me today?»",
  },
  21: {
    personality: "Wholeness, calm mastery, «I've seen cycles».",
    character: "Need to complete. Perfectionism trap.",
    health: "Whole system. Balance prevents illness.",
    love: "Mature partnership. Union of equals.",
    money: "Completion brings reward. Global thinking.",
    purpose: "Close cycles and integrate all parts.",
    talents: "International, translation, large projects.",
    family: "Род — migrants, world citizens.",
    children: "Wisdom for next generation.",
    career: "Scale matters. Finish what you start.",
    karma: "Урок — done is better than perfect.",
    spirit: "Комfort — travel, wholeness practices.",
    practice: "Finish one hanging task per week.",
  },
  22: {
    personality: "Freedom, spontaneity, youthfulness.",
    character: "Fear of commitment vs need for adventure.",
    health: "Nerves, legs, breathing. Routine helps.",
    love: "Light start, depth if partner gives space.",
    money: "Unusual income paths. Risk without plan hurts.",
    purpose: "Trust life and walk new paths.",
    talents: "Travel, startup, humor, improvisation.",
    family: "Род — wanderers, rebels, artists.",
    children: "Playful parent or late choice.",
    career: "Portfolio career. Freedom non-negotiable.",
    karma: "Урок — freedom with responsibility.",
    spirit: "Комfort — road, sky, new experiences.",
    practice: "One small commitment you keep daily.",
  },
};

export type SphereField = keyof Omit<ArcanaDepth, "practice">;

const SPHERE_FIELD: Record<string, SphereField> = {
  personality: "personality",
  character: "character",
  health: "health",
  love: "love",
  money: "money",
  purpose: "purpose",
  talents: "talents",
  family: "family",
  children: "children",
  career: "career",
  karma: "karma",
  spirit: "spirit",
};

export function getArcanaSphereText(sphereId: string, arcana: number): string {
  const depth = ARCANA_DEPTH[arcana];
  if (!depth) return "";
  const field = SPHERE_FIELD[sphereId] ?? "personality";
  return `${depth[field]} ${depth.practice}`;
}

export function getArcanaLabel(arcana: number): string {
  return arcanaLabel(arcana);
}
